browser1=chrome   
browser2=edge
url=https://petstore.octoperf.com
timeout=10
LoginExcelData=C:\\practice_files\\selenium\\mini_P\\MiniProject\\testdata\\testdata.xlsx
site.landingPage.title=JPetStore Demo
site.landingPage.heading=Welcome to JPetStore 6
site.landingPage.footer=Copyright www.mybatis.org
site.categoryPage.url=https://petstore.octoperf.com/actions/Catalog.action
site.categoryPage.searchToken=Do
site.cartPage.headingText=Shopping Cart
site.checkoutPage.headingText=Payment Details
